# -*- coding: utf-8 -*-
"""Supply Chain Demand Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1POTMDymfwIHes2HNU-wmo3oEOghzmiuH

# **Step 1 - Loading the libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# **Step 2 - Loading Dataset**"""

df = pd.read_csv("/content/demand_forecasting.csv")
df

"""# **Step 3 - Undersatanding the Dataset**"""

df.head()

df.tail()

df.shape

df.info

df.describe()

df.columns

"""# **Step 4 - Cleaning the Data**"""

df.isnull().sum()

plt.figure(figsize=(10,5))
sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
plt.title('Missing Values Heatmap')
plt.show()

df.drop_duplicates()

df = df.drop(columns="Epidemic")

df = df.drop(columns="Store ID")

df

df.shape

df.describe()

"""# **Importing Libraries**"""

!pip install pytorch-lightning
!pip install pytorch-forecasting
!pip install shap

!pip install tensorflow

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

import shap

df.dtypes

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col].astype(str))

le = LabelEncoder()

categorical_cols = [
    'Product ID',
    'Category',
    'Region',
    'Weather Condition',
    'Seasonality'
]

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

df.dtypes

"""# **Step 6 - Data Visualization**

Demand Distribution
"""

plt.figure(figsize=(8,5))
sns.histplot(df['Demand'], bins=30, kde=True)
plt.title('Demand Distribution')
plt.xlabel('Demand')
plt.ylabel('Frequency')

plt.show()

"""Sales Trend"""

plt.figure(figsize=(12,6))
plt.plot(df['Units Sold'][:500])
plt.title('Units Sold Trend')
plt.xlabel('Records')
plt.ylabel('Units Sold')

plt.show()

"""Correlation Heatmap"""

plt.figure(figsize=(14,8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')

plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x='Category', y='Demand', data=df)
plt.title('Category-wise Demand')

plt.show()

"""# **Step 6 - Model Training and Evaluation**"""

X = df.drop(['Demand', 'Date'], axis=1)
y = df['Demand']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

"""# **Step 7 -LSTM Model**

Reshaping Data for LSTM
"""

X_train_lstm = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_test_lstm = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))

model = Sequential()
model.add(LSTM(64, return_sequences=True,
               input_shape=(X_train_lstm.shape[1],1)))

model.add(Dropout(0.2))
model.add(LSTM(32))
model.add(Dropout(0.2))
model.add(Dense(1))

model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

model.summary()

"""Training the model"""

history = model.fit(
    X_train_lstm,
    y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

"""Prediction"""

predictions = model.predict(X_test_lstm)

"""Evaluation"""

mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, predictions)

print('MAE:', mae)
print('MSE:', mse)
print('RMSE:', rmse)
print('R2 Score:', r2)

"""Graph for Actual vs Predicted"""

plt.figure(figsize=(12,6))
plt.plot(y_test.values[:100], label='Actual')
plt.plot(predictions[:100], label='Predicted')

plt.legend()
plt.title('Actual vs Predicted Demand')

plt.show()

"""# **Step 8 - Transformer Model**

Importing Necessary Libraries
"""

from tensorflow.keras.layers import MultiHeadAttention
from tensorflow.keras.layers import LayerNormalization
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model

inputs = Input(shape=(X_train_lstm.shape[1],1))

attention = MultiHeadAttention(
    num_heads=2,
    key_dim=2
)(inputs, inputs)

x = LayerNormalization()(attention)
x = Dense(64, activation='relu')(x)
x = tf.keras.layers.Flatten()(x)
outputs = Dense(1)(x)

transformer_model = Model(inputs, outputs)

transformer_model.compile(
    optimizer='adam',
    loss='mse'
)

transformer_model.summary()

transformer_model.fit(
    X_train_lstm,
    y_train,
    epochs=5,
    batch_size=32
)

"""# **Step 9 - SHAP**"""

X_train_flat = X_train_lstm.reshape(X_train_lstm.shape[0], -1)
X_test_flat = X_test_lstm.reshape(X_test_lstm.shape[0], -1)

# Prediction function
def model_predict(data):

    data = data.reshape(
        data.shape[0],
        X_train_lstm.shape[1],
        1
    )

    return model.predict(data)

# Background data
background = X_train_flat[:100]

# Create SHAP Explainer
explainer = shap.KernelExplainer(
    model_predict,
    background
)

# Generate SHAP values
shap_values = explainer.shap_values(
    X_test_flat[:50]
)

# Convert SHAP values properly
shap_values = np.array(shap_values)

# Summary Plot
plt.figure(figsize=(14,8))

shap.summary_plot(
    shap_values.squeeze(),
    X_test_flat[:50],
    feature_names=list(X.columns),
    show=False
)

plt.title("SHAP Feature Importance - Supply Chain Forecasting")

plt.show()

"""# **Step 10 - Temporal Fusion Transformer (TFT)**"""

from pytorch_forecasting import TimeSeriesDataSet
from pytorch_forecasting import TemporalFusionTransformer

print('Temporal Fusion Transformer imported successfully')

"""Forecasting Visualization"""

plt.figure(figsize=(10,6))
plt.plot(predictions[:200], label='Forecasted Demand')

plt.title('Supply Chain Demand Forecasting')
plt.xlabel('Samples')
plt.ylabel('Demand')
plt.legend()

plt.show()